// api/auth.js
// This endpoint starts the Notion OAuth login flow.
// When the user clicks "Login with Notion", the extension opens this URL.
// This file redirects them to Notion's authorization page.

export default function handler(req, res) {
  // The 'state' is a unique ID generated by the extension to track this login session
  const state = req.query.state;

  if (!state) {
    return res.status(400).json({ error: 'Missing state parameter' });
  }

  const clientId = process.env.NOTION_CLIENT_ID;
  const redirectUri = `https://${req.headers.host}/api/callback`;

  // Build the Notion OAuth URL
  const notionAuthUrl =
    `https://api.notion.com/v1/oauth/authorize` +
    `?client_id=${encodeURIComponent(clientId)}` +
    `&response_type=code` +
    `&owner=user` +
    `&redirect_uri=${encodeURIComponent(redirectUri)}` +
    `&state=${encodeURIComponent(state)}`;

  // Send the user to Notion's login page
  res.redirect(302, notionAuthUrl);
}
